name: StaffChat
version: '${project.version}'
main: org.synth.StaffChat
api-version: '1.20'
commands:
  staffchat:
    description: All of staff chat commands
    usage: /staffchat [toggle]
    aliases: [sc]
